trigger: none
pr: none
# can replace the git hub action build and push trigger
# tags:
#   include:
#   - v2.*
resources:
  repositories:
    - repository: devops
      type: github
      endpoint: MapColonies
      name: MapColonies/Devops
      ref: refs/heads/master

variables:
  HELM_EXPERIMENTAL_OCI: 1

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: aro-nonprod-pool
        steps:
          - checkout: self
          - template: azure-pipelines/buildAndPush.yaml@devops
            parameters:
              dockerfilePaths:
                - name: osm-change-generator-server
                  path: '$(Build.SourcesDirectory)/Dockerfile'
              appName: 'osm-change-generator-server'
