{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm-change-generator-server.name" . -}}
{{- $cloudProviderFlavor := include "osm-change-generator-server.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "osm-change-generator-server.environment" . }}
    release: {{ $releaseName }}
    {{- include "osm-change-generator-server.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "osm-change-generator-server.selectorLabels" . | nindent 4 }}
{{- end }}
