{{- $releaseName := .Release.Name -}}
{{- $chartName := include "change-generator.name" . -}}
{{- $cloudProviderFlavor := include "change-generator.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "change-generator.fullname" .) }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "change-generator.environment" . }}
    release: {{ $releaseName }}
    {{- include "change-generator.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "change-generator.selectorLabels" . | nindent 4 }}
{{- end }}
